"use client";
import React, { useState, useRef, useCallback, useEffect } from "react";
import { motion } from "framer-motion";
import { Loader2, Save, Sparkles, BookOpen, X, Play, FileText } from "lucide-react";
import { generateFlashcardsWithAuth, saveFlashcardSetWithAuth, Flashcard } from "@/lib/actions/flashcard-actions";
import FlashcardStudyView from "./FlashcardStudyView";
import toast from "react-hot-toast";

interface FlashcardGeneratorProps {
  pdfId: string;
  pageNumber: number;
  docTitle?: string;
  selectedText?: string;
  chatAction?: 'add' | 'explain' | 'summarize' | 'flashcards';
  onClearSelectedText?: () => void;
  totalPages?: number; // ✅ NEW: Add total pages prop
  // ✅ NEW: Flashcard persistence props
  onFlashcardGenerated?: (flashcards: Flashcard[], title: string) => void;
  onFlashcardSaved?: () => void;
  onFlashcardClear?: () => void;
  persistentFlashcards?: {
    flashcards: Flashcard[];
    title: string;
    isSaved: boolean;
  } | null;
}

// ✅ NEW: Function to extract text from PDF page using existing text layer
const extractPageText = async (pageNumber: number): Promise<string> => {
  try {
    // Wait a bit for the PDF to be fully rendered
    await new Promise(resolve => setTimeout(resolve, 500));

    // Find the PDF viewer container - try multiple selectors
    let pdfContainer = document.querySelector('.react-pdf__Page');
    if (!pdfContainer) {
      pdfContainer = document.querySelector('[data-page-number]');
    }
    if (!pdfContainer) {
      pdfContainer = document.querySelector('.react-pdf__Page__canvas');
    }

    if (!pdfContainer) {
      throw new Error('PDF viewer not found. Please ensure the PDF is loaded.');
    }

    // Find the text layer within the PDF page
    let textLayer = pdfContainer.querySelector('.react-pdf__Page__textContent');
    if (!textLayer) {
      textLayer = pdfContainer.querySelector('.textLayer');
    }
    if (!textLayer) {
      // Try to find any text elements directly
      const textElements = pdfContainer.querySelectorAll('span, div');
      if (textElements.length > 0) {
        const textArray: string[] = [];
        textElements.forEach((element) => {
          const text = element.textContent?.trim();
          if (text && text.length > 0) {
            textArray.push(text);
          }
        });

        if (textArray.length > 0) {
          const fullText = textArray.join(' ').replace(/\s+/g, ' ').trim();
          if (fullText) {
            return fullText;
          }
        }
      }
      throw new Error('Text layer not found. The PDF might not have selectable text.');
    }

    // Get all text elements
    const textElements = textLayer.querySelectorAll('span');
    if (textElements.length === 0) {
      // Try alternative selectors
      const altTextElements = textLayer.querySelectorAll('div, p, span');
      if (altTextElements.length === 0) {
        throw new Error('No text elements found. The PDF might be image-based.');
      }

      const textArray: string[] = [];
      altTextElements.forEach((element) => {
        const text = element.textContent?.trim();
        if (text && text.length > 0) {
          textArray.push(text);
        }
      });

      if (textArray.length === 0) {
        throw new Error('No text content found. The PDF might be image-based or not fully loaded.');
      }

      const fullText = textArray.join(' ').replace(/\s+/g, ' ').trim();
      return fullText;
    }

    // Extract text from all elements
    const textArray: string[] = [];
    textElements.forEach((element) => {
      const text = element.textContent?.trim();
      if (text && text.length > 0) {
        textArray.push(text);
      }
    });

    // Combine all text with proper spacing
    const fullText = textArray.join(' ').replace(/\s+/g, ' ').trim();

    if (!fullText) {
      throw new Error('No text content found. The PDF might be image-based.');
    }

    return fullText;
  } catch (error) {
    console.error('Error extracting page text:', error);
    throw new Error('Failed to extract text from page. Please ensure the PDF is fully loaded and contains selectable text.');
  }
};

// ✅ UPDATED: Responsive Flashcard Preview Component
const FlashcardPreview: React.FC<{
  flashcards: Flashcard[];
  onSave: (title: string) => void;
  onClose: () => void;
  isSaving: boolean;
  onStudy: () => void;
  autoGeneratedTitle: string;
  isSaved?: boolean;
  onClearChat?: () => void;
}> = ({ flashcards, onSave, onClose, isSaving, onStudy, autoGeneratedTitle, isSaved = false, onClearChat }) => {
  const [title, setTitle] = useState(autoGeneratedTitle);

  // Update title when autoGeneratedTitle changes
  useEffect(() => {
    setTitle(autoGeneratedTitle);
  }, [autoGeneratedTitle]);

  const handleSave = () => {
    if (isSaved) {
      console.log("Flashcards are already saved");
      return;
    }

    if (title.trim()) {
      onSave(title.trim());
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="flex flex-col h-full"
    >
      {/* ✅ UPDATED: Responsive Header */}
      <div className="flex items-center justify-between flex-shrink-0">
        <h3 className="text-base sm:text-lg font-semibold text-white">Generated Flashcards</h3>
        <button
          onClick={onClose}
          className="p-1 sm:p-1.5 rounded hover:bg-white/10 transition"
        >
          <X className="w-4 h-4 sm:w-5 sm:h-5 text-gray-400" />
        </button>
      </div>

      {/* ✅ UPDATED: Flashcards List with More Height */}
      <div className="flex-1 min-h-0 space-y-2 sm:space-y-3 overflow-y-auto custom-scrollbar">
        {flashcards.map((card, index) => (
          <div
            key={index}
            className="bg-black/20 border border-white/10 rounded-lg p-2 sm:p-3"
          >
            <div className="flex items-center gap-1 sm:gap-2 mb-1 sm:mb-2">
              <span className="text-xs bg-purple-600/50 text-purple-200 px-1.5 sm:px-2 py-0.5 sm:py-1 rounded">
                Card {index + 1}
              </span>
              <span className={`text-xs px-1.5 sm:px-2 py-0.5 sm:py-1 rounded ${
                card.difficulty_level === 'easy' ? 'bg-green-600/50 text-green-200' :
                card.difficulty_level === 'medium' ? 'bg-yellow-600/50 text-yellow-200' :
                'bg-red-600/50 text-red-200'
              }`}>
                {card.difficulty_level}
              </span>
            </div>
            <div className="space-y-1">
              <div>
                <span className="text-xs font-medium text-purple-300">Q:</span>
                <p className="text-white text-xs mt-0.5 sm:mt-1 line-clamp-2">{card.question}</p>
              </div>
              <div>
                <span className="text-xs font-medium text-green-300">A:</span>
                <p className="text-gray-300 text-xs mt-0.5 sm:mt-1 line-clamp-2">{card.answer}</p>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* ✅ UPDATED: Bottom Section with Input and Buttons */}
      <div className="flex-shrink-0 space-y-2 sm:space-y-3 pt-3 sm:pt-4">
        {/* ✅ UPDATED: Responsive Input */}
        <div className="space-y-1">
          <label className="text-xs text-gray-300">Set Title:</label>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="Enter a title for this flashcard set..."
            className="w-full px-2 sm:px-3 py-1.5 sm:py-2 bg-black/40 border border-white/10 rounded-lg text-white placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-400 text-xs sm:text-sm"
          />
        </div>

        {/* ✅ UPDATED: Action Buttons - Sticky to Bottom */}
        <div className="flex flex-col sm:flex-row gap-2 justify-center">
          <button
            onClick={onStudy}
            className="flex items-center justify-center gap-1 sm:gap-2 px-4 py-2 bg-green-600 hover:bg-green-700 transition text-white rounded-lg font-medium text-xs sm:text-sm"
          >
            <Play className="w-3 h-3 sm:w-4 sm:h-4" />
            <span className="hidden sm:inline">Study Now</span>
            <span className="sm:hidden">Study</span>
          </button>
          <button
            onClick={handleSave}
            disabled={!title.trim() || isSaving || isSaved}
            className={`flex items-center justify-center gap-1 sm:gap-2 px-4 py-2 transition text-white rounded-lg font-medium text-xs sm:text-sm ${
              isSaved
                ? 'bg-gray-600 cursor-not-allowed'
                : 'bg-purple-600 hover:bg-purple-700 disabled:opacity-50'
            }`}
          >
            {isSaving ? (
              <>
                <Loader2 className="w-3 h-3 sm:w-4 sm:h-4 animate-spin" />
                <span className="hidden sm:inline">Saving...</span>
                <span className="sm:hidden">Save...</span>
              </>
            ) : isSaved ? (
              <>
                <Save className="w-3 h-3 sm:w-4 sm:h-4" />
                <span className="hidden sm:inline">Saved</span>
                <span className="sm:hidden">Saved</span>
              </>
            ) : (
              <>
                <Save className="w-3 h-3 sm:w-4 sm:h-4" />
                <span className="hidden sm:inline">Save Set</span>
                <span className="sm:hidden">Save</span>
              </>
            )}
          </button>
          {/* ✅ NEW: Clear Chat Button */}
          {onClearChat && (
            <button
              onClick={onClearChat}
              className="flex items-center justify-center gap-1 sm:gap-2 px-4 py-2 bg-red-600 hover:bg-red-700 transition text-white rounded-lg font-medium text-xs sm:text-sm"
            >
              <X className="w-3 h-3 sm:w-4 sm:h-4" />
              <span className="hidden sm:inline">Clear Chat</span>
              <span className="sm:hidden">Clear</span>
            </button>
          )}
        </div>
      </div>
    </motion.div>
  );
};

export const FlashcardGenerator: React.FC<FlashcardGeneratorProps> = ({
  pdfId,
  pageNumber,
  docTitle,
  selectedText,
  chatAction,
  onClearSelectedText,
  totalPages,
  onFlashcardGenerated,
  onFlashcardSaved,
  onFlashcardClear,
  persistentFlashcards
}) => {
  const [content, setContent] = useState("");
  const [flashcards, setFlashcards] = useState<Flashcard[]>(persistentFlashcards?.flashcards || []);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showPreview, setShowPreview] = useState(!!persistentFlashcards);
  const [autoGeneratedTitle, setAutoGeneratedTitle] = useState(persistentFlashcards?.title || "");
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const [studyMode, setStudyMode] = useState<{ isOpen: boolean; flashcards: Flashcard[]; title: string }>({
    isOpen: false,
    flashcards: [],
    title: ""
  });
  const [isFlashcardsSaved, setIsFlashcardsSaved] = useState(persistentFlashcards?.isSaved || false);

  // ✅ NEW: Page selection state for text extraction
  const [selectedPage, setSelectedPage] = useState<number | null>(null);
  const [isExtractingText, setIsExtractingText] = useState(false);
  const [pageContext, setPageContext] = useState<string>("");
  const [showPageDropdown, setShowPageDropdown] = useState(false);

  // ✅ NEW: Handle selectedText prop for context-aware text selection
  useEffect(() => {
    if (selectedText && selectedText.trim()) {
      const trimmedText = selectedText.trim();
      setContent(trimmedText);

      // Focus the textarea after setting content
      if (textareaRef.current) {
        textareaRef.current.focus();
        textareaRef.current.setSelectionRange(trimmedText.length, trimmedText.length);
      }

      // Call the callback to clear the selected text
      if (onClearSelectedText) {
        onClearSelectedText();
      }

      // ✅ NEW: Auto-generate flashcards only when triggered by Create Flashcards action
      // Check if this is from the Create Flashcards action (not Add to Chat or Copy)
      if (trimmedText && chatAction === 'flashcards') {
        // Small delay to ensure content is set and state is updated
        setTimeout(async () => {
          setIsGenerating(true);
          setError(null);

          try {
            const result = await generateFlashcardsWithAuth(trimmedText, pdfId, pageNumber);

            if (result.success && result.flashcards) {
              setFlashcards(result.flashcards);
              setAutoGeneratedTitle(result.flashcard_title || `Flashcards - ${docTitle || 'PDF'} Page ${pageNumber}`);
              setShowPreview(true);
              setIsFlashcardsSaved(false);
            } else {
              setError(result.error || "Failed to generate flashcards");
            }
          } catch (err) {
            setError("Failed to generate flashcards. Please try again.");
          } finally {
            setIsGenerating(false);
          }
        }, 200);
      }
    }
  }, [selectedText, onClearSelectedText, pdfId, pageNumber, docTitle, chatAction]);

  // ✅ UPDATED: Responsive auto-resize functionality
  const handleTextareaResize = useCallback(() => {
    const textarea = textareaRef.current;
    if (textarea) {
      textarea.style.height = 'auto';
      const newHeight = Math.min(Math.max(textarea.scrollHeight, 80), window.innerWidth < 768 ? 200 : 300);
      textarea.style.height = newHeight + 'px';
    }
  }, []);

  // Handle content change with auto-resize
  const handleContentChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setContent(e.target.value);
    handleTextareaResize();
  };

  // ✅ NEW: Handle page text extraction
  const handleExtractPageText = async (pageNum: number) => {
    if (!pageNum || pageNum < 1 || (totalPages && pageNum > totalPages)) {
      setError(`Please select a valid page number between 1 and ${totalPages || 'unknown'}.`);
      return;
    }

    setIsExtractingText(true);
    setError(null);

    try {
      // First, navigate to the specified page if it's different from current page
      if (pageNum !== pageNumber) {
        // Dispatch a custom event to notify the parent component to change page
        const pageChangeEvent = new CustomEvent('changePage', {
          detail: { page: pageNum }
        });
        window.dispatchEvent(pageChangeEvent);

        // Wait for the page to load
        await new Promise(resolve => setTimeout(resolve, 1000));
      }

      const extractedText = await extractPageText(pageNum);

      if (extractedText.trim()) {
        setPageContext(extractedText);
        setSelectedPage(pageNum);
        console.log(`✅ Extracted text from page ${pageNum}:`, extractedText.substring(0, 100) + '...');
      } else {
        setError(`No text found on page ${pageNum}.`);
      }
    } catch (err) {
      setError("Failed to extract text from the specified page. Please try again.");
      console.error('Text extraction error:', err);
    } finally {
      setIsExtractingText(false);
    }
  };

  // ✅ NEW: Handle page selection from dropdown
  const handlePageSelect = async (pageNum: number) => {
    setSelectedPage(pageNum);
    setShowPageDropdown(false);
    await handleExtractPageText(pageNum);
  };

  // ✅ NEW: Clear page context
  const handleClearPageContext = () => {
    setPageContext("");
    setSelectedPage(null);
    setError(null);
  };

  // ✅ NEW: Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      const target = event.target as Element;
      if (!target.closest('.page-dropdown')) {
        setShowPageDropdown(false);
      }
    };

    if (showPageDropdown) {
      document.addEventListener('mousedown', handleClickOutside);
    }

    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [showPageDropdown]);

  // ✅ NEW: Handle persistent flashcards updates
  useEffect(() => {
    if (persistentFlashcards) {
      setFlashcards(persistentFlashcards.flashcards);
      setAutoGeneratedTitle(persistentFlashcards.title);
      setShowPreview(true);
      setIsFlashcardsSaved(persistentFlashcards.isSaved);
    } else {
      // Clear local state when persistent flashcards are cleared
      setFlashcards([]);
      setAutoGeneratedTitle("");
      setShowPreview(false);
      setIsFlashcardsSaved(false);
    }
  }, [persistentFlashcards]);

  const handleGenerate = async () => {
    // Use page context if available, otherwise use textarea content
    const contentToUse = pageContext || content;

    if (!contentToUse.trim()) {
      setError("Please enter some content or select a page to generate flashcards from.");
      return;
    }

    setIsGenerating(true);
    setError(null);

    try {
      const result = await generateFlashcardsWithAuth(contentToUse, pdfId, selectedPage || pageNumber);

      if (result.success && result.flashcards) {
        const title = result.flashcard_title || `Flashcards - ${docTitle || 'PDF'} Page ${selectedPage || pageNumber}`;
        setFlashcards(result.flashcards);
        setAutoGeneratedTitle(title);
        setShowPreview(true);
        setIsFlashcardsSaved(false);

        // ✅ NEW: Notify parent component about generated flashcards
        if (onFlashcardGenerated) {
          onFlashcardGenerated(result.flashcards, title);
        }
      } else {
        setError(result.error || "Failed to generate flashcards");
      }
    } catch (err) {
      setError("Failed to generate flashcards. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSave = async (title: string) => {
    setIsSaving(true);
    setError(null);

    try {
      const result = await saveFlashcardSetWithAuth(
        flashcards,
        title,
        pdfId,
        pageNumber,
        content
      );

      if (result.success) {
        // Clear form and show success
        setContent("");
        setFlashcards([]);
        setShowPreview(false);
        setAutoGeneratedTitle("");
        setIsFlashcardsSaved(true);

        // Update study mode if it's open
        if (studyMode.isOpen) {
          setStudyMode(prev => ({
            ...prev,
            flashcards: prev.flashcards // Keep the same flashcards but mark as saved
          }));
        }

        // ✅ NEW: Notify parent component about saved flashcards
        if (onFlashcardSaved) {
          onFlashcardSaved();
        }

        // Reset textarea height
        if (textareaRef.current) {
          textareaRef.current.style.height = 'auto';
        }

        // ✅ NEW: Show success toast
        toast.success("Saved to My sets", {
          duration: 3000,
          position: "bottom-right",
          style: {
            background: "#1f2937",
            color: "#f9fafb",
            border: "1px solid #374151",
          },
        });

        console.log("Flashcard set saved successfully!");
      } else {
        setError(result.error || "Failed to save flashcard set");
      }
    } catch (err) {
      setError("Failed to save flashcard set. Please try again.");
    } finally {
      setIsSaving(false);
    }
  };

  const handleClosePreview = () => {
    setShowPreview(false);
    setFlashcards([]);
    setAutoGeneratedTitle("");
  };

  const handleStudy = () => {
    if (flashcards.length > 0) {
      setStudyMode({
        isOpen: true,
        flashcards: flashcards,
        title: autoGeneratedTitle || `Generated Set - ${docTitle || 'PDF'}`
      });
    }
  };

  const closeStudyMode = () => {
    setStudyMode({
      isOpen: false,
      flashcards: [],
      title: ""
    });
  };

  // ✅ NEW: Handle clear chat
  const handleClearChat = () => {
    setShowPreview(false);
    setFlashcards([]);
    setAutoGeneratedTitle("");
    setIsFlashcardsSaved(false);
    setContent("");
    setPageContext("");
    setSelectedPage(null);

    // ✅ NEW: Notify parent component to clear persistent flashcards
    if (onFlashcardClear) {
      onFlashcardClear();
    }
  };

  return (
    <div className="flex flex-col h-full">
      {!showPreview ? (
        <>
          {/* ✅ NEW: Page Selection Section */}
          <div className="flex-shrink-0 mb-3 sm:mb-4">
            <div className="bg-black/20 border border-white/10 rounded-lg p-3 sm:p-4">
              <div className="flex items-center gap-2 sm:gap-3 mb-2">
                <FileText className="w-4 h-4 sm:w-5 sm:h-5 text-purple-400 flex-shrink-0" />
                <h4 className="text-sm sm:text-base font-medium text-white">Page Context</h4>
              </div>

              {/* ✅ NEW: Modern Page Dropdown */}
              <div className="flex flex-col sm:flex-row gap-2 sm:gap-3">
                <div className="flex-1 relative page-dropdown">
                  <button
                    onClick={() => setShowPageDropdown(!showPageDropdown)}
                    className="w-full px-3 py-2 bg-black/40 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-400 text-sm flex items-center justify-between hover:bg-black/50 transition"
                  >
                    <span className={selectedPage ? "text-white" : "text-gray-400"}>
                      {selectedPage ? `Page ${selectedPage}` : `Select page (1-${totalPages || '?'})`}
                    </span>
                    <svg className={`w-4 h-4 transition-transform ${showPageDropdown ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                    </svg>
                  </button>

                  {/* ✅ NEW: Dropdown Menu */}
                  {showPageDropdown && (
                    <div className="absolute top-full left-0 right-0 mt-1 bg-black/90 border border-white/10 rounded-lg shadow-xl z-10 max-h-48 overflow-y-auto custom-scrollbar">
                      {Array.from({ length: totalPages || 1 }, (_, i) => i + 1).map((pageNum) => (
                        <button
                          key={pageNum}
                          onClick={() => handlePageSelect(pageNum)}
                          className={`w-full px-3 py-2 text-left text-sm hover:bg-purple-600/20 transition ${
                            selectedPage === pageNum ? 'bg-purple-600/30 text-purple-200' : 'text-gray-300'
                          }`}
                        >
                          Page {pageNum}
                        </button>
                      ))}
                    </div>
                  )}
                </div>

                                 {/* ✅ NEW: Page Context Button */}
                 {selectedPage && pageContext && (
                   <button
                     onClick={handleClearPageContext}
                     className="flex items-center justify-center gap-2 px-4 py-2 bg-gray-600 hover:bg-red-600 transition-all duration-300 text-white rounded-lg font-medium text-sm group"
                     title="Clear context"
                   >
                     <FileText className="w-4 h-4" />
                     <span className="hidden sm:inline group-hover:hidden transition-all duration-300">Page in Context</span>
                     <span className="sm:hidden group-hover:hidden transition-all duration-300">Context</span>
                     <span className="hidden group-hover:inline transition-all duration-300">Clear Context</span>
                   </button>
                 )}
              </div>

              {/* ✅ NEW: Current Page Quick Access */}
              <div className="flex items-center gap-2 mt-2">
                <button
                  onClick={async () => {
                    setIsExtractingText(true);
                    setError(null);

                    try {
                      const extractedText = await extractPageText(pageNumber);
                      if (extractedText.trim()) {
                        setPageContext(extractedText);
                        setSelectedPage(pageNumber);
                        console.log(`✅ Extracted text from current page ${pageNumber}:`, extractedText.substring(0, 100) + '...');
                      } else {
                        setError(`No text found on current page ${pageNumber}.`);
                      }
                    } catch (err) {
                      setError("Failed to extract text from current page. Please try again.");
                      console.error('Text extraction error:', err);
                    } finally {
                      setIsExtractingText(false);
                    }
                  }}
                  disabled={isExtractingText}
                                     className="flex items-center justify-center gap-1 px-3 py-1.5 bg-slate-700 hover:bg-slate-600 disabled:opacity-50 disabled:cursor-not-allowed transition text-white rounded text-xs"
                >
                  <FileText className="w-3 h-3" />
                  <span>Current Page ({pageNumber})</span>
                </button>
                {totalPages && (
                  <span className="text-xs text-gray-400">
                    Total pages: {totalPages}
                  </span>
                )}
              </div>
            </div>
          </div>

          {/* ✅ UPDATED: Content Area with More Height */}
          <div className="flex-1 flex flex-col space-y-3 sm:space-y-4 min-h-0">
            {/* ✅ UPDATED: Responsive Content Input */}
            <div className="flex-1">
              <div className="relative h-full">
                <textarea
                  ref={textareaRef}
                  id="content"
                  rows={4}
                  maxLength={5000}
                  className="w-full h-full min-h-[120px] sm:min-h-[200px] resize-none rounded-lg bg-black/40 border border-white/10 px-2 sm:px-3 py-2 sm:py-3 text-white placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-400 text-xs sm:text-sm transition custom-scrollbar"
                  placeholder={pageContext ? "Add additional content here (optional)..." : "Paste content here or select a page above..."}
                  value={content}
                  onChange={handleContentChange}
                  disabled={isGenerating}
                />
                {content.trim() && (
                  <button
                    onClick={() => setContent("")}
                    className="absolute top-2 right-3 p-1 rounded bg-gray-700/50 hover:bg-gray-600/50 text-gray-300 hover:text-white transition"
                    title="Clear content"
                  >
                    <X className="w-3 h-3" />
                  </button>
                )}
              </div>
            </div>

            {/* ✅ UPDATED: Responsive Error Display */}
            {error && (
              <div className="text-red-400 text-xs sm:text-sm bg-red-900/20 border border-red-500/20 rounded-lg p-2 sm:p-3 flex-shrink-0">
                ❌ {error}
              </div>
            )}
          </div>

          {/* ✅ UPDATED: Generate Button - Sticky to Bottom */}
          <div className="flex-shrink-0 pt-3 sm:pt-4">
            <div className="flex justify-center">
                             <button
                 onClick={handleGenerate}
                 disabled={(!content.trim() && !pageContext) || isGenerating}
                 className="px-4 py-2 bg-purple-600 hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition text-white rounded-lg flex items-center justify-center gap-1.5 sm:gap-2 text-xs sm:text-sm"
               >
                {isGenerating ? (
                  <>
                    <Loader2 className="w-3 h-3 sm:w-4 sm:h-4 animate-spin" />
                    <span className="hidden sm:inline">Generating Flashcards...</span>
                    <span className="sm:hidden">Generating...</span>
                  </>
                ) : (
                  <>
                    <BookOpen className="w-3 h-3 sm:w-4 sm:h-4" />
                    <span className="hidden sm:inline">Generate Flashcards</span>
                    <span className="sm:hidden">Generate</span>
                  </>
                )}
              </button>
            </div>
          </div>
        </>
      ) : (
        <div className="flex flex-col h-full">
          {/* ✅ UPDATED: Flashcard Preview with More Height */}
          <div className="flex-1 min-h-0">
            <FlashcardPreview
              flashcards={flashcards}
              onSave={handleSave}
              onClose={handleClosePreview}
              isSaving={isSaving}
              onStudy={handleStudy}
              autoGeneratedTitle={autoGeneratedTitle}
              isSaved={isFlashcardsSaved}
              onClearChat={handleClearChat}
            />
          </div>
        </div>
      )}

      {/* ✅ UPDATED: Responsive Study Mode Modal */}
      {studyMode.isOpen && (
        <FlashcardStudyView
          flashcards={studyMode.flashcards}
          onClose={closeStudyMode}
          title={studyMode.title}
          pdfId={pdfId}
          pageNumber={pageNumber}
          content={content}
          isSaved={isFlashcardsSaved}
          onSaved={() => setIsFlashcardsSaved(true)}
        />
      )}
    </div>
  );
};

export default FlashcardGenerator;