"use client";
import React, { useState, useRef, useCallback, useEffect } from "react";
import { motion } from "framer-motion";
import { Loader2, Save, Sparkles, BookOpen, X, Play } from "lucide-react";
import { generateFlashcardsWithAuth, saveFlashcardSetWithAuth, Flashcard } from "@/lib/actions/flashcard-actions";
import FlashcardStudyView from "./FlashcardStudyView";

interface FlashcardGeneratorProps {
  pdfId: string;
  pageNumber: number;
  docTitle?: string;
  selectedText?: string;
  chatAction?: 'add' | 'explain' | 'summarize';
  onClearSelectedText?: () => void;
}

// ✅ UPDATED: Responsive Flashcard Preview Component
const FlashcardPreview: React.FC<{
  flashcards: Flashcard[];
  onSave: (title: string) => void;
  onClose: () => void;
  isSaving: boolean;
  onStudy: () => void;
  autoGeneratedTitle: string;
}> = ({ flashcards, onSave, onClose, isSaving, onStudy, autoGeneratedTitle }) => {
  const [title, setTitle] = useState(autoGeneratedTitle);

  // Update title when autoGeneratedTitle changes
  useEffect(() => {
    setTitle(autoGeneratedTitle);
  }, [autoGeneratedTitle]);

  const handleSave = () => {
    if (title.trim()) {
      onSave(title.trim());
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="flex flex-col h-full"
    >
      {/* ✅ UPDATED: Responsive Header */}
      <div className="flex items-center justify-between flex-shrink-0">
        <h3 className="text-base sm:text-lg font-semibold text-white">Generated Flashcards</h3>
        <button
          onClick={onClose}
          className="p-1 sm:p-1.5 rounded hover:bg-white/10 transition"
        >
          <X className="w-4 h-4 sm:w-5 sm:h-5 text-gray-400" />
        </button>
      </div>

      {/* ✅ UPDATED: Flashcards List with More Height */}
      <div className="flex-1 min-h-0 space-y-2 sm:space-y-3 overflow-y-auto custom-scrollbar">
        {flashcards.map((card, index) => (
          <div
            key={index}
            className="bg-black/20 border border-white/10 rounded-lg p-2 sm:p-3"
          >
            <div className="flex items-center gap-1 sm:gap-2 mb-1 sm:mb-2">
              <span className="text-xs bg-purple-600/50 text-purple-200 px-1.5 sm:px-2 py-0.5 sm:py-1 rounded">
                Card {index + 1}
              </span>
              <span className={`text-xs px-1.5 sm:px-2 py-0.5 sm:py-1 rounded ${
                card.difficulty_level === 'easy' ? 'bg-green-600/50 text-green-200' :
                card.difficulty_level === 'medium' ? 'bg-yellow-600/50 text-yellow-200' :
                'bg-red-600/50 text-red-200'
              }`}>
                {card.difficulty_level}
              </span>
            </div>
            <div className="space-y-1">
              <div>
                <span className="text-xs font-medium text-purple-300">Q:</span>
                <p className="text-white text-xs mt-0.5 sm:mt-1 line-clamp-2">{card.question}</p>
              </div>
              <div>
                <span className="text-xs font-medium text-green-300">A:</span>
                <p className="text-gray-300 text-xs mt-0.5 sm:mt-1 line-clamp-2">{card.answer}</p>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* ✅ UPDATED: Bottom Section with Input and Buttons */}
      <div className="flex-shrink-0 space-y-2 sm:space-y-3 pt-3 sm:pt-4">
        {/* ✅ UPDATED: Responsive Input */}
        <div className="space-y-1">
          <label className="text-xs text-gray-300">Set Title:</label>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="Enter a title for this flashcard set..."
            className="w-full px-2 sm:px-3 py-1.5 sm:py-2 bg-black/40 border border-white/10 rounded-lg text-white placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-400 text-xs sm:text-sm"
          />
        </div>

        {/* ✅ UPDATED: Action Buttons - Sticky to Bottom */}
        <div className="flex flex-col sm:flex-row gap-2 justify-center">
          <button
            onClick={onStudy}
            className="flex items-center justify-center gap-1 sm:gap-2 px-4 py-2 bg-green-600 hover:bg-green-700 transition text-white rounded-lg font-medium text-xs sm:text-sm"
          >
            <Play className="w-3 h-3 sm:w-4 sm:h-4" />
            <span className="hidden sm:inline">Study Now</span>
            <span className="sm:hidden">Study</span>
          </button>
          <button
            onClick={handleSave}
            disabled={!title.trim() || isSaving}
            className="flex items-center justify-center gap-1 sm:gap-2 px-4 py-2 bg-purple-600 hover:bg-purple-700 disabled:opacity-50 transition text-white rounded-lg font-medium text-xs sm:text-sm"
          >
            {isSaving ? (
              <>
                <Loader2 className="w-3 h-3 sm:w-4 sm:h-4 animate-spin" />
                <span className="hidden sm:inline">Saving...</span>
                <span className="sm:hidden">Save...</span>
              </>
            ) : (
              <>
                <Save className="w-3 h-3 sm:w-4 sm:h-4" />
                <span className="hidden sm:inline">Save Set</span>
                <span className="sm:hidden">Save</span>
              </>
            )}
          </button>
        </div>
      </div>
    </motion.div>
  );
};

export const FlashcardGenerator: React.FC<FlashcardGeneratorProps> = ({
  pdfId,
  pageNumber,
  docTitle,
  selectedText,
  chatAction,
  onClearSelectedText
}) => {
  const [content, setContent] = useState("");
  const [flashcards, setFlashcards] = useState<Flashcard[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showPreview, setShowPreview] = useState(false);
  const [autoGeneratedTitle, setAutoGeneratedTitle] = useState("");
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const [studyMode, setStudyMode] = useState<{ isOpen: boolean; flashcards: Flashcard[]; title: string }>({
    isOpen: false,
    flashcards: [],
    title: ""
  });

  // ✅ NEW: Handle selectedText prop for context-aware text selection
  useEffect(() => {
    if (selectedText && selectedText.trim()) {
      const trimmedText = selectedText.trim();
      setContent(trimmedText);

      // Focus the textarea after setting content
      if (textareaRef.current) {
        textareaRef.current.focus();
        textareaRef.current.setSelectionRange(trimmedText.length, trimmedText.length);
      }

      // Call the callback to clear the selected text
      if (onClearSelectedText) {
        onClearSelectedText();
      }

      // ✅ NEW: Auto-generate flashcards when selectedText is provided
      if (trimmedText) {
        // Small delay to ensure content is set and state is updated
        setTimeout(async () => {
          setIsGenerating(true);
          setError(null);

          try {
            const result = await generateFlashcardsWithAuth(trimmedText, pdfId, pageNumber);

            if (result.success && result.flashcards) {
              setFlashcards(result.flashcards);
              setAutoGeneratedTitle(result.flashcard_title || `Flashcards - ${docTitle || 'PDF'} Page ${pageNumber}`);
              setShowPreview(true);
            } else {
              setError(result.error || "Failed to generate flashcards");
            }
          } catch (err) {
            setError("Failed to generate flashcards. Please try again.");
          } finally {
            setIsGenerating(false);
          }
        }, 200);
      }
    }
  }, [selectedText, onClearSelectedText, pdfId, pageNumber, docTitle]);

  // ✅ UPDATED: Responsive auto-resize functionality
  const handleTextareaResize = useCallback(() => {
    const textarea = textareaRef.current;
    if (textarea) {
      textarea.style.height = 'auto';
      const newHeight = Math.min(Math.max(textarea.scrollHeight, 80), window.innerWidth < 768 ? 200 : 300);
      textarea.style.height = newHeight + 'px';
    }
  }, []);

  // Handle content change with auto-resize
  const handleContentChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setContent(e.target.value);
    handleTextareaResize();
  };

  const handleGenerate = async () => {
    if (!content.trim()) {
      setError("Please enter some content to generate flashcards from.");
      return;
    }

    setIsGenerating(true);
    setError(null);

    try {
      const result = await generateFlashcardsWithAuth(content, pdfId, pageNumber);

      if (result.success && result.flashcards) {
        setFlashcards(result.flashcards);
        setAutoGeneratedTitle(result.flashcard_title || `Flashcards - ${docTitle || 'PDF'} Page ${pageNumber}`);
        setShowPreview(true);
      } else {
        setError(result.error || "Failed to generate flashcards");
      }
    } catch (err) {
      setError("Failed to generate flashcards. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSave = async (title: string) => {
    setIsSaving(true);
    setError(null);

    try {
      const result = await saveFlashcardSetWithAuth(
        flashcards,
        title,
        pdfId,
        pageNumber,
        content
      );

      if (result.success) {
        // Clear form and show success
        setContent("");
        setFlashcards([]);
        setShowPreview(false);
        setAutoGeneratedTitle("");
        // Reset textarea height
        if (textareaRef.current) {
          textareaRef.current.style.height = 'auto';
        }
        // You could add a success toast here
        console.log("Flashcard set saved successfully!");
      } else {
        setError(result.error || "Failed to save flashcard set");
      }
    } catch (err) {
      setError("Failed to save flashcard set. Please try again.");
    } finally {
      setIsSaving(false);
    }
  };

  const handleClosePreview = () => {
    setShowPreview(false);
    setFlashcards([]);
    setAutoGeneratedTitle("");
  };

  const handleStudy = () => {
    if (flashcards.length > 0) {
      setStudyMode({
        isOpen: true,
        flashcards: flashcards,
        title: autoGeneratedTitle || `Generated Set - ${docTitle || 'PDF'}`
      });
    }
  };

  const closeStudyMode = () => {
    setStudyMode({
      isOpen: false,
      flashcards: [],
      title: ""
    });
  };

  return (
    <div className="flex flex-col h-full">
      {!showPreview ? (
        <>
          {/* ✅ UPDATED: Content Area with More Height */}
          <div className="flex-1 flex flex-col space-y-3 sm:space-y-4 min-h-0">
            {/* ✅ UPDATED: Responsive Content Input */}
            <div className="flex-1">
              <div className="relative h-full">
                <textarea
                  ref={textareaRef}
                  id="content"
                  rows={4}
                  maxLength={5000}
                  className="w-full h-full min-h-[120px] sm:min-h-[200px] resize-none rounded-lg bg-black/40 border border-white/10 px-2 sm:px-3 py-2 sm:py-3 text-white placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-400 text-xs sm:text-sm transition"
                  placeholder="Paste the page content here..."
                  value={content}
                  onChange={handleContentChange}
                  disabled={isGenerating}
                />
                {content.trim() && (
                  <button
                    onClick={() => setContent("")}
                    className="absolute top-2 right-3 p-1 rounded bg-gray-700/50 hover:bg-gray-600/50 text-gray-300 hover:text-white transition"
                    title="Clear content"
                  >
                    <X className="w-3 h-3" />
                  </button>
                )}
              </div>
            </div>

            {/* ✅ UPDATED: Responsive Error Display */}
            {error && (
              <div className="text-red-400 text-xs sm:text-sm bg-red-900/20 border border-red-500/20 rounded-lg p-2 sm:p-3 flex-shrink-0">
                ❌ {error}
              </div>
            )}
          </div>

          {/* ✅ UPDATED: Generate Button - Sticky to Bottom */}
          <div className="flex-shrink-0 pt-3 sm:pt-4">
            <div className="flex justify-center">
              <button
                onClick={handleGenerate}
                disabled={!content.trim() || isGenerating}
                className="px-4 py-2 bg-purple-600 hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition text-white rounded-lg flex items-center justify-center gap-1.5 sm:gap-2 text-xs sm:text-sm"
              >
                {isGenerating ? (
                  <>
                    <Loader2 className="w-3 h-3 sm:w-4 sm:h-4 animate-spin" />
                    <span className="hidden sm:inline">Generating Flashcards...</span>
                    <span className="sm:hidden">Generating...</span>
                  </>
                ) : (
                  <>
                    <BookOpen className="w-3 h-3 sm:w-4 sm:h-4" />
                    <span className="hidden sm:inline">Generate Flashcards</span>
                    <span className="sm:hidden">Generate</span>
                  </>
                )}
              </button>
            </div>
          </div>
        </>
      ) : (
        <div className="flex flex-col h-full">
          {/* ✅ UPDATED: Flashcard Preview with More Height */}
          <div className="flex-1 min-h-0">
            <FlashcardPreview
              flashcards={flashcards}
              onSave={handleSave}
              onClose={handleClosePreview}
              isSaving={isSaving}
              onStudy={handleStudy}
              autoGeneratedTitle={autoGeneratedTitle}
            />
          </div>
        </div>
      )}

      {/* ✅ UPDATED: Responsive Study Mode Modal */}
      {studyMode.isOpen && (
        <FlashcardStudyView
          flashcards={studyMode.flashcards}
          onClose={closeStudyMode}
          title={studyMode.title}
        />
      )}
    </div>
  );
};

export default FlashcardGenerator;