"use client";
import React, { useState, useRef, useCallback, useEffect } from "react";
import { motion } from "framer-motion";
import { Loader2, Save, Sparkles, BookOpen, X, Play, CheckCircle, XCircle, FileText } from "lucide-react";
import { generateQuizWithAuth, saveQuizSetWithAuth, QuizQuestion } from "@/lib/actions/quiz-actions";
import QuizTakeView from "./QuizTakeView";
import toast from "react-hot-toast";

interface QuizGeneratorProps {
  pdfId: string;
  pageNumber: number;
  docTitle?: string;
  selectedText?: string;
  chatAction?: 'add' | 'explain' | 'summarize' | 'flashcards';
  onClearSelectedText?: () => void;
  totalPages?: number; // ✅ NEW: Add total pages prop
  // ✅ NEW: Quiz persistence props
  onQuizGenerated?: (questions: QuizQuestion[], title: string) => void;
  onQuizSaved?: () => void;
  onQuizClear?: () => void;
  persistentQuiz?: {
    questions: QuizQuestion[];
    title: string;
    isSaved: boolean;
  } | null;
}

// ✅ NEW: Function to extract text from PDF page using existing text layer
const extractPageText = async (pageNumber: number): Promise<string> => {
  try {
    // Wait a bit for the PDF to be fully rendered
    await new Promise(resolve => setTimeout(resolve, 500));

    // Find the PDF viewer container - try multiple selectors
    let pdfContainer = document.querySelector('.react-pdf__Page');
    if (!pdfContainer) {
      pdfContainer = document.querySelector('[data-page-number]');
    }
    if (!pdfContainer) {
      pdfContainer = document.querySelector('.react-pdf__Page__canvas');
    }

    if (!pdfContainer) {
      throw new Error('PDF viewer not found. Please ensure the PDF is loaded.');
    }

    // Find the text layer within the PDF page
    let textLayer = pdfContainer.querySelector('.react-pdf__Page__textContent');
    if (!textLayer) {
      textLayer = pdfContainer.querySelector('.textLayer');
    }
    if (!textLayer) {
      // Try to find any text elements directly
      const textElements = pdfContainer.querySelectorAll('span, div');
      if (textElements.length > 0) {
        const textArray: string[] = [];
        textElements.forEach((element) => {
          const text = element.textContent?.trim();
          if (text && text.length > 0) {
            textArray.push(text);
          }
        });

        if (textArray.length > 0) {
          const fullText = textArray.join(' ').replace(/\s+/g, ' ').trim();
          if (fullText) {
            return fullText;
          }
        }
      }
      throw new Error('Text layer not found. The PDF might not have selectable text.');
    }

    // Get all text elements
    const textElements = textLayer.querySelectorAll('span');
    if (textElements.length === 0) {
      // Try alternative selectors
      const altTextElements = textLayer.querySelectorAll('div, p, span');
      if (altTextElements.length === 0) {
        throw new Error('No text elements found. The PDF might be image-based.');
      }

      const textArray: string[] = [];
      altTextElements.forEach((element) => {
        const text = element.textContent?.trim();
        if (text && text.length > 0) {
          textArray.push(text);
        }
      });

      if (textArray.length === 0) {
        throw new Error('No text content found. The PDF might be image-based or not fully loaded.');
      }

      const fullText = textArray.join(' ').replace(/\s+/g, ' ').trim();
      return fullText;
    }

    // Extract text from all elements
    const textArray: string[] = [];
    textElements.forEach((element) => {
      const text = element.textContent?.trim();
      if (text && text.length > 0) {
        textArray.push(text);
      }
    });

    // Combine all text with proper spacing
    const fullText = textArray.join(' ').replace(/\s+/g, ' ').trim();

    if (!fullText) {
      throw new Error('No text content found. The PDF might be image-based.');
    }

    return fullText;
  } catch (error) {
    console.error('Error extracting page text:', error);
    throw new Error('Failed to extract text from page. Please ensure the PDF is fully loaded and contains selectable text.');
  }
};

// ✅ UPDATED: Responsive Quiz Preview Component
const QuizPreview: React.FC<{
  questions: QuizQuestion[];
  onSave: (title: string) => void;
  onClose: () => void;
  isSaving: boolean;
  onTakeQuiz: () => void;
  autoGeneratedTitle: string;
  isSaved?: boolean;
  onClearChat?: () => void;
}> = ({ questions, onSave, onClose, isSaving, onTakeQuiz, autoGeneratedTitle, isSaved = false, onClearChat }) => {
  const [title, setTitle] = useState(autoGeneratedTitle);

  // Update title when autoGeneratedTitle changes
  useEffect(() => {
    setTitle(autoGeneratedTitle);
  }, [autoGeneratedTitle]);

  const handleSave = () => {
    if (isSaved) {
      console.log("Quiz is already saved");
      return;
    }

    if (title.trim()) {
      onSave(title.trim());
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="flex flex-col h-full"
    >
      {/* ✅ UPDATED: Responsive Header */}
      <div className="flex items-center justify-between flex-shrink-0">
        <h3 className="text-base sm:text-lg font-semibold text-white">Generated Quiz Questions</h3>
        <button
          onClick={onClose}
          className="p-1 sm:p-1.5 rounded hover:bg-white/10 transition"
        >
          <X className="w-4 h-4 sm:w-5 sm:h-5 text-gray-400" />
        </button>
      </div>

      {/* ✅ UPDATED: Questions List with More Height */}
      <div className="flex-1 min-h-0 space-y-2 sm:space-y-3 overflow-y-auto custom-scrollbar">
        {questions.map((question, index) => (
          <div
            key={index}
            className="bg-black/20 border border-white/10 rounded-lg p-2 sm:p-3"
          >
            <div className="flex items-center gap-1 sm:gap-2 mb-1 sm:mb-2">
              <span className="text-xs bg-purple-600/50 text-purple-200 px-1.5 sm:px-2 py-0.5 sm:py-1 rounded">
                Question {index + 1}
              </span>
              <span className={`text-xs px-1.5 sm:px-2 py-0.5 sm:py-1 rounded ${
                question.difficulty_level === 'easy' ? 'bg-green-600/50 text-green-200' :
                question.difficulty_level === 'medium' ? 'bg-yellow-600/50 text-yellow-200' :
                'bg-red-600/50 text-red-200'
              }`}>
                {question.difficulty_level}
              </span>
            </div>

            <div className="space-y-1 sm:space-y-2">
              <div>
                <span className="text-xs font-medium text-purple-300">Q:</span>
                <p className="text-white text-xs mt-0.5 sm:mt-1 line-clamp-2">{question.question}</p>
              </div>

              <div className="space-y-0.5 sm:space-y-1">
                <div className="flex items-center gap-1 sm:gap-2">
                  <span className="w-3 h-3 sm:w-4 sm:h-4 rounded-full flex items-center justify-center text-xs font-medium bg-gray-600 text-gray-300">
                    A
                  </span>
                  <span className="text-gray-300 text-xs line-clamp-1">{question.option_a}</span>
                </div>

                <div className="flex items-center gap-1 sm:gap-2">
                  <span className="w-3 h-3 sm:w-4 sm:h-4 rounded-full flex items-center justify-center text-xs font-medium bg-gray-600 text-gray-300">
                    B
                  </span>
                  <span className="text-gray-300 text-xs line-clamp-1">{question.option_b}</span>
                </div>

                <div className="flex items-center gap-1 sm:gap-2">
                  <span className="w-3 h-3 sm:w-4 sm:h-4 rounded-full flex items-center justify-center text-xs font-medium bg-gray-600 text-gray-300">
                    C
                  </span>
                  <span className="text-gray-300 text-xs line-clamp-1">{question.option_c}</span>
                </div>

                <div className="flex items-center gap-1 sm:gap-2">
                  <span className="w-3 h-3 sm:w-4 sm:h-4 rounded-full flex items-center justify-center text-xs font-medium bg-gray-600 text-gray-300">
                    D
                  </span>
                  <span className="text-gray-300 text-xs line-clamp-1">{question.option_d}</span>
                </div>
              </div>

              <div className="mt-1 sm:mt-2 p-1.5 sm:p-2 bg-blue-900/20 border border-blue-500/20 rounded text-xs text-blue-200">
                <span className="font-medium">💡 Hint:</span> Take the quiz to see explanations and correct answers!
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* ✅ UPDATED: Bottom Section with Input and Buttons */}
      <div className="flex-shrink-0 space-y-2 sm:space-y-3 pt-3 sm:pt-4">
        {/* ✅ UPDATED: Responsive Input */}
        <div className="space-y-1">
          <label className="text-xs text-gray-300">Quiz Title:</label>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="Enter a title for this quiz..."
            className="w-full px-2 sm:px-3 py-1.5 sm:py-2 bg-black/40 border border-white/10 rounded-lg text-white placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-400 text-xs sm:text-sm"
          />
        </div>

        {/* ✅ UPDATED: Action Buttons - Sticky to Bottom */}
        <div className="flex flex-col sm:flex-row gap-2 justify-center">
          <button
            onClick={onTakeQuiz}
            className="flex items-center justify-center gap-1 sm:gap-2 px-4 py-2 bg-green-600 hover:bg-green-700 transition text-white rounded-lg font-medium text-xs sm:text-sm"
          >
            <Play className="w-3 h-3 sm:w-4 sm:h-4" />
            <span className="hidden sm:inline">Take Quiz Now</span>
            <span className="sm:hidden">Take Quiz</span>
          </button>
          <button
            onClick={handleSave}
            disabled={!title.trim() || isSaving || isSaved}
            className={`flex items-center justify-center gap-1 sm:gap-2 px-4 py-2 transition text-white rounded-lg font-medium text-xs sm:text-sm ${
              isSaved
                ? 'bg-gray-600 cursor-not-allowed'
                : 'bg-purple-600 hover:bg-purple-700 disabled:opacity-50'
            }`}
          >
            {isSaving ? (
              <>
                <Loader2 className="w-3 h-3 sm:w-4 sm:h-4 animate-spin" />
                <span className="hidden sm:inline">Saving...</span>
                <span className="sm:hidden">Save...</span>
              </>
            ) : isSaved ? (
              <>
                <Save className="w-3 h-3 sm:w-4 sm:h-4" />
                <span className="hidden sm:inline">Saved</span>
                <span className="sm:hidden">Saved</span>
              </>
            ) : (
              <>
                <Save className="w-3 h-3 sm:w-4 sm:h-4" />
                <span className="hidden sm:inline">Save Quiz</span>
                <span className="sm:hidden">Save</span>
              </>
            )}
          </button>
          {/* ✅ NEW: Clear Chat Button */}
          {onClearChat && (
            <button
              onClick={onClearChat}
              className="flex items-center justify-center gap-1 sm:gap-2 px-4 py-2 bg-red-600 hover:bg-red-700 transition text-white rounded-lg font-medium text-xs sm:text-sm"
            >
              <X className="w-3 h-3 sm:w-4 sm:h-4" />
              <span className="hidden sm:inline">Clear Chat</span>
              <span className="sm:hidden">Clear</span>
            </button>
          )}
        </div>
      </div>
    </motion.div>
  );
};

export const QuizGenerator: React.FC<QuizGeneratorProps> = ({
  pdfId,
  pageNumber,
  docTitle,
  selectedText,
  chatAction,
  onClearSelectedText,
  totalPages,
  onQuizGenerated,
  onQuizSaved,
  onQuizClear,
  persistentQuiz
}) => {
  const [content, setContent] = useState("");
  const [questions, setQuestions] = useState<QuizQuestion[]>(persistentQuiz?.questions || []);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showPreview, setShowPreview] = useState(!!persistentQuiz);
  const [autoGeneratedTitle, setAutoGeneratedTitle] = useState(persistentQuiz?.title || "");
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const [quizMode, setQuizMode] = useState<{ isOpen: boolean; questions: QuizQuestion[]; title: string; quizSetId?: string }>({
    isOpen: false,
    questions: [],
    title: "",
    quizSetId: undefined
  });
  const [isQuizSaved, setIsQuizSaved] = useState(persistentQuiz?.isSaved || false);
  const [hasShownSaveToast, setHasShownSaveToast] = useState(false);

  // ✅ NEW: Multi-page selection state for text extraction
  const [selectedPages, setSelectedPages] = useState<number[]>([]);
  const [isExtractingText, setIsExtractingText] = useState(false);
  const [pageContexts, setPageContexts] = useState<Map<number, string>>(new Map());
  const [showPageDropdown, setShowPageDropdown] = useState(false);
  const [showSelectedPagesModal, setShowSelectedPagesModal] = useState(false);

  // ✅ NEW: Handle selectedText prop for context-aware text selection
  useEffect(() => {
    if (selectedText && selectedText.trim()) {
      setContent(selectedText.trim());
      // Focus the textarea after setting content
      if (textareaRef.current) {
        textareaRef.current.focus();
        textareaRef.current.setSelectionRange(selectedText.length, selectedText.length);
      }
      // Call the callback to clear the selected text
      if (onClearSelectedText) {
        onClearSelectedText();
      }
    }
  }, [selectedText, onClearSelectedText]);

  // ✅ UPDATED: Responsive auto-resize functionality
  const handleTextareaResize = useCallback(() => {
    const textarea = textareaRef.current;
    if (textarea) {
      textarea.style.height = 'auto';
      const newHeight = Math.min(Math.max(textarea.scrollHeight, 80), window.innerWidth < 768 ? 200 : 300);
      textarea.style.height = newHeight + 'px';
    }
  }, []);

  // Handle content change with auto-resize
  const handleContentChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setContent(e.target.value);
    handleTextareaResize();
  };

  // ✅ NEW: Handle page text extraction for multiple pages
  const handleExtractPageText = async (pageNum: number) => {
    if (!pageNum || pageNum < 1 || (totalPages && pageNum > totalPages)) {
      setError(`Please select a valid page number between 1 and ${totalPages || 'unknown'}.`);
      return;
    }

    setIsExtractingText(true);
    setError(null);

    try {
      // First, navigate to the specified page if it's different from current page
      if (pageNum !== pageNumber) {
        // Dispatch a custom event to notify the parent component to change page
        const pageChangeEvent = new CustomEvent('changePage', {
          detail: { page: pageNum }
        });
        window.dispatchEvent(pageChangeEvent);

        // Wait for the page to load
        await new Promise(resolve => setTimeout(resolve, 1000));
      }

      const extractedText = await extractPageText(pageNum);

      if (extractedText.trim()) {
        // Add to page contexts map
        setPageContexts(prev => new Map(prev).set(pageNum, extractedText));
        // Add to selected pages if not already included
        setSelectedPages(prev => prev.includes(pageNum) ? prev : [...prev, pageNum]);
        console.log(`✅ Extracted text from page ${pageNum}:`, extractedText.substring(0, 100) + '...');
      } else {
        setError(`No text found on page ${pageNum}.`);
      }
    } catch (err) {
      setError("Failed to extract text from the specified page. Please try again.");
      console.error('Text extraction error:', err);
    } finally {
      setIsExtractingText(false);
    }
  };

  // ✅ NEW: Handle page selection from dropdown
  const handlePageSelect = async (pageNum: number) => {
    setShowPageDropdown(false);
    await handleExtractPageText(pageNum);
  };

  // ✅ NEW: Clear specific page context
  const handleClearPageContext = (pageNum?: number) => {
    if (pageNum) {
      // Clear specific page
      setPageContexts(prev => {
        const newMap = new Map(prev);
        newMap.delete(pageNum);
        return newMap;
      });
      setSelectedPages(prev => prev.filter(p => p !== pageNum));
    } else {
      // Clear all pages
      setPageContexts(new Map());
      setSelectedPages([]);
    }
    setError(null);
  };

  // ✅ NEW: Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      const target = event.target as Element;
      if (!target.closest('.page-dropdown')) {
        setShowPageDropdown(false);
      }
    };

    if (showPageDropdown) {
      document.addEventListener('mousedown', handleClickOutside);
    }

    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [showPageDropdown]);

  // ✅ NEW: Handle persistent quiz updates
  useEffect(() => {
    if (persistentQuiz) {
      setQuestions(persistentQuiz.questions);
      setAutoGeneratedTitle(persistentQuiz.title);
      setShowPreview(true);
      setIsQuizSaved(persistentQuiz.isSaved);
    } else {
      // Clear local state when persistent quiz is cleared
      setQuestions([]);
      setAutoGeneratedTitle("");
      setShowPreview(false);
      setIsQuizSaved(false);
      setHasShownSaveToast(false); // Reset toast state
    }
  }, [persistentQuiz]);

  const handleGenerate = async () => {
    // Get all page contexts and combine with manual content
    const allPageContexts = Array.from(pageContexts.values());
    const hasPageContexts = allPageContexts.length > 0;
    const hasManualContent = content.trim().length > 0;

    if (!hasManualContent && !hasPageContexts) {
      setError("Please add some content or select pages to generate quiz questions.");
      return;
    }

    setIsGenerating(true);
    setError(null);

    try {
      // Combine all page contexts and manual content
      let combinedContent = "";

      if (hasPageContexts) {
        combinedContent = allPageContexts.join('\n\n--- Page Break ---\n\n');
      }

      if (hasManualContent) {
        combinedContent = combinedContent
          ? `${combinedContent}\n\n--- Additional Content ---\n\n${content}`
          : content;
      }

      const result = await generateQuizWithAuth(combinedContent, pdfId, pageNumber);

      if (result.success && result.quiz_questions) {
        setQuestions(result.quiz_questions);
        const pageInfo = selectedPages.length > 0 ? `Pages ${selectedPages.join(', ')}` : `Page ${pageNumber}`;
        setAutoGeneratedTitle(result.quiz_title || `Quiz - ${docTitle || 'PDF'} ${pageInfo}`);
        setShowPreview(true);
        setIsQuizSaved(false);
        setHasShownSaveToast(false); // Reset toast state for new quiz

        // ✅ NEW: Notify parent component about generated quiz
        if (onQuizGenerated) {
          onQuizGenerated(result.quiz_questions, result.quiz_title || `Quiz - ${docTitle || 'PDF'} ${pageInfo}`);
        }
      } else {
        setError(result.error || "Failed to generate quiz questions");
      }
    } catch (err) {
      setError("Failed to generate quiz questions. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSave = async (title: string) => {
    // Don't save if already saved
    if (isQuizSaved) {
      console.log("Quiz is already saved, skipping save operation");
      return { success: true };
    }

    console.log("Saving quiz with title:", title);

    setIsSaving(true);
    setError(null);

    try {
      const result = await saveQuizSetWithAuth(
        questions,
        title,
        pdfId,
        pageNumber,
        content
      );

      if (result.success) {
        // Clear form and show success
        setContent("");
        setQuestions([]);
        setShowPreview(false);
        setAutoGeneratedTitle("");
        setIsQuizSaved(true);

        // ✅ NEW: Notify parent component about saved quiz
        if (onQuizSaved) {
          onQuizSaved();
        }

        // Reset textarea height
        if (textareaRef.current) {
          textareaRef.current.style.height = 'auto';
        }

        // ✅ NEW: Show success toast only if not shown yet
        // if (!hasShownSaveToast) {
        //   toast.success("Saved to My sets");
        //   setHasShownSaveToast(true);
        // }

        console.log("Quiz set saved successfully!");
        return { success: true };
      } else {
        setError(result.error || "Failed to save quiz set");
        return { success: false, error: result.error };
      }
    } catch (err) {
      setError("Failed to save quiz set. Please try again.");
      return { success: false, error: "Failed to save quiz set" };
    } finally {
      setIsSaving(false);
    }
  };

  const handleClosePreview = () => {
    setShowPreview(false);
    // Don't clear questions if quiz is saved - keep them for persistence
    if (!isQuizSaved) {
      setQuestions([]);
      setAutoGeneratedTitle("");
    }
  };

  const handleTakeQuiz = () => {
    if (questions.length > 0) {
      const quizSetId = isQuizSaved ? 'saved-quiz-id' : undefined;
      console.log('Opening quiz with quizSetId:', quizSetId, 'isQuizSaved:', isQuizSaved);
      setQuizMode({
        isOpen: true,
        questions: questions,
        title: autoGeneratedTitle || `Generated Quiz - ${docTitle || 'PDF'}`,
        quizSetId: quizSetId // Pass saved status to prevent duplicate saves
      });
    }
  };

  const closeQuizMode = () => {
    setQuizMode({
      isOpen: false,
      questions: [],
      title: "",
      quizSetId: undefined
    });
  };

  // ✅ NEW: Handle clear chat
  const handleClearChat = () => {
    setShowPreview(false);
    setQuestions([]);
    setAutoGeneratedTitle("");
    setIsQuizSaved(false);
    setHasShownSaveToast(false); // Reset toast state
    setContent("");
    setPageContexts(new Map());
    setSelectedPages([]);

    // ✅ NEW: Notify parent component to clear persistent quiz
    if (onQuizClear) {
      onQuizClear();
    }
  };

  return (
    <div className="flex flex-col h-full">
      {!showPreview ? (
        <>
          {/* ✅ NEW: Page Selection Section */}
          <div className="flex-shrink-0 mb-3 sm:mb-4">
            <div className="bg-black/20 border border-white/10 rounded-lg p-3 sm:p-4">
              <div className="flex items-center gap-2 sm:gap-3 mb-2">
                <FileText className="w-4 h-4 sm:w-5 sm:h-5 text-purple-400 flex-shrink-0" />
                <h4 className="text-sm sm:text-base font-medium text-white">Page Context</h4>
              </div>

              {/* ✅ NEW: Modern Page Dropdown */}
              <div className="flex flex-col sm:flex-row gap-2 sm:gap-3">
                <div className="flex-1 relative page-dropdown">
                  <button
                    onClick={() => setShowPageDropdown(!showPageDropdown)}
                    className="w-full px-3 py-2 bg-black/40 border border-white/10 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-purple-400 text-sm flex items-center justify-between hover:bg-black/50 transition"
                  >
                    <span className={selectedPages.length > 0 ? "text-white" : "text-gray-400"}>
                      {selectedPages.length > 0 ? `${selectedPages.length} page(s) selected` : `Select pages (1-${totalPages || '?'})`}
                    </span>
                    <svg className={`w-4 h-4 transition-transform ${showPageDropdown ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                    </svg>
                  </button>

                  {/* ✅ NEW: Dropdown Menu */}
                  {showPageDropdown && (
                    <div className="absolute top-full left-0 right-0 mt-1 bg-black/90 border border-white/10 rounded-lg shadow-xl z-10 max-h-48 overflow-y-auto custom-scrollbar">
                      {Array.from({ length: totalPages || 1 }, (_, i) => i + 1).map((pageNum) => (
                        <button
                          key={pageNum}
                          onClick={() => handlePageSelect(pageNum)}
                          className={`w-full px-3 py-2 text-left text-sm hover:bg-purple-600/20 transition ${
                            selectedPages.includes(pageNum) ? 'bg-purple-600/30 text-purple-200' : 'text-gray-300'
                          }`}
                        >
                          Page {pageNum}
                        </button>
                      ))}
                    </div>
                  )}
                </div>

                {/* ✅ NEW: Selected Pages Button */}
                {selectedPages.length > 0 && (
                  <button
                    onClick={() => setShowSelectedPagesModal(true)}
                    className="flex items-center justify-center gap-2 px-3 py-2 bg-purple-600/20 hover:bg-purple-600/30 border border-purple-500/30 rounded-lg text-purple-300 hover:text-purple-200 transition-all duration-300 text-sm font-medium"
                    title="View selected pages"
                  >
                    <FileText className="w-4 h-4" />
                    <span>{selectedPages.length} page(s) selected</span>
                  </button>
                )}
              </div>

              {/* ✅ NEW: Current Page Quick Access */}
              <div className="flex items-center gap-2 mt-2">
                <button
                  onClick={async () => {
                    setIsExtractingText(true);
                    setError(null);

                    try {
                      const extractedText = await extractPageText(pageNumber);
                      if (extractedText.trim()) {
                        // Add to page contexts map
                        setPageContexts(prev => new Map(prev).set(pageNumber, extractedText));
                        // Add to selected pages if not already included
                        setSelectedPages(prev => prev.includes(pageNumber) ? prev : [...prev, pageNumber]);
                        console.log(`✅ Extracted text from current page ${pageNumber}:`, extractedText.substring(0, 100) + '...');
                      } else {
                        setError(`No text found on current page ${pageNumber}.`);
                      }
                    } catch (err) {
                      setError("Failed to extract text from current page. Please try again.");
                      console.error('Text extraction error:', err);
                    } finally {
                      setIsExtractingText(false);
                    }
                  }}
                  disabled={isExtractingText}
                  className="flex items-center justify-center gap-1 px-3 py-1.5 bg-slate-700 hover:bg-slate-600 disabled:opacity-50 disabled:cursor-not-allowed transition text-white rounded text-xs"
                >
                  <FileText className="w-3 h-3" />
                  <span>Current Page ({pageNumber})</span>
                </button>
                {totalPages && (
                  <span className="text-xs text-gray-400">
                    Total pages: {totalPages}
                  </span>
                )}
              </div>
            </div>
          </div>

          {/* ✅ UPDATED: Content Area with More Height */}
          <div className="flex-1 flex flex-col space-y-3 sm:space-y-4 min-h-0">
            {/* ✅ UPDATED: Responsive Content Input with Clear Button */}
            <div className="flex-1 flex flex-col space-y-1.5 sm:space-y-2">
              <div className="relative flex-1">
                <textarea
                  ref={textareaRef}
                  value={content}
                  onChange={handleContentChange}
                  disabled={isGenerating}
                  placeholder={selectedPages.length > 0 ? "Add additional content here (optional)..." : "Paste content here or select pages above..."}
                  className="w-full h-full min-h-[120px] sm:min-h-[200px] resize-none rounded-lg bg-black/40 border border-white/10 px-2 sm:px-3 py-2 sm:py-3 text-white placeholder:text-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-400 text-xs sm:text-sm transition-all duration-200 custom-scrollbar"
                  maxLength={5000}
                />
                {content.trim() && (
                  <button
                    onClick={() => setContent("")}
                    className="absolute top-2 right-3 p-1 rounded bg-gray-700/50 hover:bg-gray-600/50 text-gray-300 hover:text-white transition"
                    title="Clear content"
                  >
                    <X className="w-3 h-3" />
                  </button>
                )}
              </div>
            </div>

            {/* ✅ UPDATED: Responsive Error Display */}
            {error && (
              <div className="text-xs sm:text-sm text-red-400 bg-red-900/10 border border-red-500/20 rounded-lg px-2 sm:px-3 py-1.5 sm:py-2 flex-shrink-0">
                ❌ {error}
              </div>
            )}
          </div>

          {/* ✅ UPDATED: Generate Button - Sticky to Bottom */}
          <div className="flex-shrink-0 pt-3 sm:pt-4">
            <div className="flex justify-center">
              <button
                onClick={handleGenerate}
                disabled={(!content.trim() && selectedPages.length === 0) || isGenerating}
                className="px-4 py-2 bg-purple-600 hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition text-white rounded-lg flex items-center justify-center gap-1.5 sm:gap-2 text-xs sm:text-sm"
              >
                {isGenerating ? (
                  <>
                    <Loader2 className="w-3 h-3 sm:w-4 sm:h-4 animate-spin" />
                    <span className="hidden sm:inline">Generating Quiz...</span>
                    <span className="sm:hidden">Generating...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-3 h-3 sm:w-4 sm:h-4" />
                    <span className="hidden sm:inline">Generate Quiz</span>
                    <span className="sm:hidden">Generate</span>
                  </>
                )}
              </button>
            </div>
          </div>
        </>
      ) : (
        <div className="flex flex-col h-full">
          {/* ✅ UPDATED: Quiz Preview with More Height */}
                  <div className="flex-1 min-h-0">
          <QuizPreview
            questions={questions}
            onSave={handleSave}
            onClose={handleClosePreview}
            isSaving={isSaving}
            onTakeQuiz={handleTakeQuiz}
            autoGeneratedTitle={autoGeneratedTitle}
            isSaved={isQuizSaved}
            onClearChat={handleClearChat}
          />
        </div>
        </div>
      )}

      {/* ✅ UPDATED: Responsive Quiz Mode Modal */}
      {quizMode.isOpen && (
        <QuizTakeView
          questions={quizMode.questions}
          onClose={closeQuizMode}
          title={quizMode.title}
          quizSetId={quizMode.quizSetId}
          pdfId={pdfId}
          pageNumber={pageNumber}
          docTitle={docTitle}
          content={content}
          onSaveQuiz={handleSave}
          isAlreadySaved={isQuizSaved}
        />
      )}

      {/* ✅ NEW: Selected Pages Modal */}
      {showSelectedPagesModal && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-black/95 border border-white/10 rounded-lg shadow-xl max-w-md w-full max-h-[80vh] overflow-hidden">
            {/* Modal Header */}
            <div className="flex items-center justify-between p-4 border-b border-white/10">
              <h3 className="text-lg font-medium text-white">Selected Pages</h3>
              <button
                onClick={() => setShowSelectedPagesModal(false)}
                className="text-gray-400 hover:text-white transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Modal Content */}
            <div className="p-4 max-h-[60vh] overflow-y-auto">
              {selectedPages.length === 0 ? (
                <p className="text-gray-400 text-center py-4">No pages selected</p>
              ) : (
                <div className="space-y-2">
                  {selectedPages.map((pageNum) => (
                    <div key={pageNum} className="flex items-center justify-between gap-3 p-3 bg-black/30 border border-white/10 rounded-lg">
                      <div className="flex items-center gap-2">
                        <FileText className="w-4 h-4 text-purple-400" />
                        <span className="text-white">Page {pageNum}</span>
                      </div>
                      <button
                        onClick={() => {
                          handleClearPageContext(pageNum);
                          // Close modal if no pages left
                          if (selectedPages.length === 1) {
                            setShowSelectedPagesModal(false);
                          }
                        }}
                        className="text-red-400 hover:text-red-300 transition-colors p-1"
                        title="Remove this page"
                      >
                        <X className="w-4 h-4" />
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Modal Footer */}
            {selectedPages.length > 0 && (
              <div className="p-4 border-t border-white/10">
                <button
                  onClick={() => {
                    handleClearPageContext();
                    setShowSelectedPagesModal(false);
                  }}
                  className="w-full flex items-center justify-center gap-2 px-4 py-2 bg-red-600/20 hover:bg-red-600/30 border border-red-500/30 rounded-lg text-red-400 hover:text-red-300 transition-all duration-300 font-medium"
                >
                  <X className="w-4 h-4" />
                  Clear All Pages
                </button>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default QuizGenerator;